import { useParams, useNavigate } from "react-router-dom";
import { useEffect, useState } from "react";
import { fetchFullAnalysisById } from "./api";
import "./analysis.css";
import jsPDF from "jspdf";

/* ======================
   HELPERS
====================== */

// Bias label
function getBiasLabel(score) {
  if (score >= 85) return "Highly Biased";
  if (score >= 65) return "Moderately Biased";
  return "Mostly Neutral";
}
// Bias color class
function getBiasClass(score) {
  if (score >= 85) return "bias-red";
  if (score >= 65) return "bias-yellow";
  return "bias-green";
}

// Full report formatter for TXT
function formatFullReport(data) {
  return `
==============================
NewsRoom AI Co-Writer - Full Report
==============================

TITLE
------------------------------
${data?.title || "N/A"}

ARTICLE
------------------------------
${data?.content || "N/A"}

BIAS SCORE
------------------------------
${data?.bias_score ?? 0} / 100
Label: ${getBiasLabel(data?.bias_score ?? 0)}

EXPLANATION
------------------------------
${data?.explanation || "N/A"}

NEUTRAL SUMMARY
------------------------------
${data?.summary || "N/A"}

ALTERNATIVE PERSPECTIVES
------------------------------
${(data?.perspectives || []).map((p, i) => `${i + 1}. ${p}`).join("\n")}

DEEP ANALYSIS
------------------------------

PASSIONIT:
${JSON.stringify(data?.deep_analysis?.PASSIONIT || {}, null, 2)}

PRUTL:
${JSON.stringify(data?.deep_analysis?.PRUTL || {}, null, 2)}

GOVERNANCE / SOUL / CULTURE:
${JSON.stringify(data?.deep_analysis?.governance_soul_culture || {}, null, 2)}

ETHICS & LONG-TERM CONSEQUENCES:
${data?.deep_analysis?.kalki_aidharma || "N/A"}

==============================
Generated by NewsRoom AI Co-Writer
==============================
`.trim();
}

// TXT download
function downloadTXT(data) {
  const reportText = formatFullReport(data);
  const blob = new Blob([reportText], { type: "text/plain" });
  const url = URL.createObjectURL(blob);

  const a = document.createElement("a");
  a.href = url;
  a.download = `NewsRoom_Report_${data?.id}.txt`;
  a.click();

  URL.revokeObjectURL(url);
}

// PDF download
function downloadPDF(data) {
  const doc = new jsPDF("p", "pt", "a4");
  const pageWidth = doc.internal.pageSize.getWidth() - 40;
  let y = 30;

  const addSection = (title, content) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text(title, 20, y);
    y += 16;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    const lines = doc.splitTextToSize(content || "N/A", pageWidth);
    doc.text(lines, 20, y);
    y += lines.length * 12 + 10;
  };

  addSection("TITLE", data?.title);
  addSection("ARTICLE", data?.content);
  addSection(
    "BIAS SCORE",
    `${data?.bias_score ?? 0} / 100 (${getBiasLabel(data?.bias_score ?? 0)})`,
  );
  addSection("EXPLANATION", data?.explanation);
  addSection("NEUTRAL SUMMARY", data?.summary);

  addSection("ALTERNATIVE PERSPECTIVES", (data?.perspectives || []).join("\n"));

  addSection(
    "DEEP ANALYSIS - PASSIONIT",
    JSON.stringify(data?.deep_analysis?.PASSIONIT || {}, null, 2),
  );

  addSection(
    "DEEP ANALYSIS - PRUTL",
    JSON.stringify(data?.deep_analysis?.PRUTL || {}, null, 2),
  );

  addSection(
    "DEEP ANALYSIS - GOVERNANCE / SOUL / CULTURE",
    JSON.stringify(data?.deep_analysis?.governance_soul_culture || {}, null, 2),
  );

  addSection(
    "DEEP ANALYSIS - ETHICS & LONG-TERM CONSEQUENCES",
    data?.deep_analysis?.kalki_aidharma,
  );

  doc.save(`NewsRoom_Report_${data?.id}.pdf`);
}

/* ======================
   PAGE COMPONENT
===================== */

export default function AnalysisPage() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [downloadOpen, setDownloadOpen] = useState(false);

  useEffect(() => {
    fetchFullAnalysisById(id)
      .then(setData)
      .catch((err) => {
        console.error("Analysis fetch failed:", err);
        setData(null);
      })

      .finally(() => setLoading(false));
  }, [id]);

  useEffect(() => {
    const handleClickOutside = (e) => {
      if (!e.target.closest(".download-container")) {
        setDownloadOpen(false);
      }
    };
    document.addEventListener("click", handleClickOutside);
    return () => document.removeEventListener("click", handleClickOutside);
  }, []);

  if (loading) return <p className="analysis-loading">Loading analysis...</p>;
  if (!data) return <p className="analysis-loading">No data found</p>;

  return (
    <div className="analysis-scroll">
      <div className="analysis-page">
        {/* TOP BAR */}
        <div className="analysis-topbar">
          <button
            className="back-btn"
            onClick={() => navigate(`/?articleId=${id}`)}
          >
            ← Back to Editor
          </button>

          <div className="analysis-title">
            Deep Analysis Report
            <span
              className={`bias-badge ${getBiasClass(data?.bias_score ?? 0)}`}
            >
              Bias: {data?.bias_score ?? 0}/100 (
              {getBiasLabel(data?.bias_score ?? 0)})
            </span>
          </div>

          <div className="download-container">
            <button
              className="download-btn"
              onClick={() => setDownloadOpen(!downloadOpen)}
            >
              ⬇ Download
            </button>

            {downloadOpen && (
              <div className="download-options">
                <button onClick={() => downloadTXT(data)}>Download TXT</button>
                <button onClick={() => downloadPDF(data)}>Download PDF</button>
              </div>
            )}
          </div>
        </div>

        {/* GRID */}
        <div className="analysis-grid">
          <div className="analysis-card">
            <div className="section-label">SOURCE ARTICLE</div>
            <h1 className="article-title">{data?.title}</h1>
            <div className="article-text">{data?.content}</div>
          </div>

          <div className="analysis-card">
            <div className="section-label">STRUCTURED ANALYSIS</div>

            <Accordion title="PASSIONIT (9 Dimensions)">
              {renderObject(data?.deep_analysis?.PASSIONIT)}
            </Accordion>

            <Accordion title="PRUTL (Moral–Material)">
              {renderObject(data?.deep_analysis?.PRUTL)}
            </Accordion>

            <Accordion title="Governance • Soul • Culture">
              {renderObject(data?.deep_analysis?.governance_soul_culture)}
            </Accordion>

            <Accordion title="Kalki-Aidharma (Archetypal)">
              <p>{data?.deep_analysis?.kalki_aidharma || "N/A"}</p>
            </Accordion>
          </div>
        </div>
      </div>
    </div>
  );
}

/* ======================
   COMPONENTS
===================== */

function Accordion({ title, children }) {
  const [open, setOpen] = useState(false);

  return (
    <div className="accordion">
      <button className="accordion-header" onClick={() => setOpen(!open)}>
        <span>{title}</span>
        <span>{open ? "▲" : "▼"}</span>
      </button>
      {open && <div className="accordion-body">{children}</div>}
    </div>
  );
}

function renderObject(obj) {
  if (!obj || typeof obj !== "object") {
    return <p className="muted">No data available.</p>;
  }

  return Object.entries(obj).map(([k, v]) => (
    <p key={k}>
      <strong>{k.replaceAll("_", " ")}:</strong>{" "}
      {typeof v === "object" ? JSON.stringify(v) : String(v)}
    </p>
  ));
}
